#!/usr/bin/env bash
# Neofetch config file

# Speed up script by not using unicode
export LC_ALL=C
export LANG=C

print_info() {
    info title
    info underline
    info "OS" distro
    info "Model" model
    info "Kernel" kernel
    info "Shell" shell
    info "DE" de
    info "Terminal" term
    info "CPU" cpu
    info "Memory" memory
    info "CPU Usage" cpu_usage
    info line_break
    info cols
    info line_break
}

# Kernel

kernel_shorthand="off"

# Distro

distro_shorthand="off"
os_arch="on"

# Shell

shell_path="off"
shell_version="on"

# CPU

speed_type="bios"
cpu_shorthand="off"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="on"

# Text Colors

colors=(distro)

# Text Options

bold="on"
underline_enabled="on"
underline_char="-"

# Color Blocks

color_blocks="off"

# Progress Bars

bar_char_elapsed="-"
bar_char_total="="
bar_border="on"
bar_length=15
bar_color_elapsed="distro"
bar_color_total="distro"
# bar:     '[---=======]'
# infobar: 'info [---=======]'
# barinfo: '[---=======] info'
# off:     'info'
cpu_display="barinfo"
memory_display="barinfo"
battery_display="off"
disk_display="off"

# Image Options

image_source="ascii"
gap=2

# Ascii Options

ascii="distro"
ascii_distro="auto"
ascii_colors=(distro)
ascii_logo_size="normal"
ascii_bold="on"

# Scrot Options

scrot="off"

# Config Options

config="on"
config_file="${XDG_CONFIG_HOME:-${HOME}/.config}/neofetch/config"
